#!/bin/sh

# ensure homebrew installation
if command -v brew >/dev/null; then
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

brew install git

cd ~/Documents

if [ ! -d macOS-imaging-script ]; then
	git clone https://github.com/ChrisOlsonFilms/macOS-imaging-script.git
fi

cd macOS-imaging-script

./install-macos-apps.sh
./install-symlinks.sh
./install-preferences.sh
