#!/bin/sh

echo "install applications"
brew bundle install
brew services start skhd

echo "installing yabai -sa"
sudo yabai --install-sa

echo "apps to manually download"
Black magic speedtest
Offload
Plural Eyes
DJI Assistant
Clover Configurator
Canon utility
Logitech gaming software
